// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/22/2025, 4:29:52 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/blogadmin/voidtales-portal/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/blogadmin/voidtales-portal/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/blogadmin/voidtales-portal/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/blogadmin/voidtales-portal/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/blogadmin/voidtales-portal/plugins/**/*.{js,ts,mjs}","/home/blogadmin/voidtales-portal/composables/**/*.{js,ts,mjs}","/home/blogadmin/voidtales-portal/utils/**/*.{js,ts,mjs}","/home/blogadmin/voidtales-portal/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/blogadmin/voidtales-portal/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/blogadmin/voidtales-portal/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/blogadmin/voidtales-portal/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;